### ISSUE TITLE
momentary grab & drag randomly "latches" and won't let go until i click again

### ISSUE THREAD

**Issue by walterw2** [davidparsson/scrollbar-anywhere#39]
i have it set to show the little 4-way arrow when i left-click to grab; i can't seem to determine a pattern, it just half the time won't "let go" unless i click again.

**Comment by deathtrip** [comment]
will this be fixed?
it happens for me on both linux and windows
makes the extension pretty much unusable

**Comment by deathtrip** [comment]
here's the debug:
Uncaught TypeError: Failed to execute 'collapse' on 'Selection': 1 argument required, but only 0 present. onMouseUp
Apparently newer releases of google-chrome requires that the 'collapse' function takes at least one argument.

**Comment by davidparsson** [comment]
Thanks for the info. That will make it easier to fix. I'll try to find some time to look into this, but in the meantime, pull requests are most welcome!

**Comment by davidparsson** [comment]
Fix finally released in v2.8.

Ping @walterw2, @deathtrip.
