### ISSUE TITLE
Feature request: Exclude this site feature implementation

### ISSUE THREAD

**Issue by Droyk** [davidparsson/scrollbar-anywhere#53]
Hey @davidparsson we meet again how are you hope you are great 
First I am sorry to trouble you again but I can't help it I want this extension to be a great extension. 

**Exclude this site feature implementation** this feature will work when the site isn't compatible with scrollbar at all isn't compatible means scrollbar only scrolls on the page and doesn't interact with elements of the page at all like gmail, some parts of youtube, steam and many more sites.

I want this ublock origin kind of excluding feature which look like this 
![screenshot_20161209103843](https://cloud.githubusercontent.com/assets/15848350/21078250/524a4484-bf8e-11e6-86ab-3b4e4f712985.png)
**_thanx for reading it._**

**Comment by davidparsson** [comment]
@Droyk, are you saying that you want some way to disable this extension on certain selected sites?

**Comment by Droyk** [comment]
Yup I want this ublock origin kind of excluding feature it disable's the extension on websites or pages.
![screenshot_20161209103843](https://cloud.githubusercontent.com/assets/15848350/21078250/524a4484-bf8e-11e6-86ab-3b4e4f712985.png)

**Comment by metadirective** [comment]
+1  Would love this feature too as i prefer to avoid extra keys to scroll. 

Unfortunately sites like Mindomo (mind mapping) are perturbed which oblige me to add an extra key for the whole web as there's no exclude list.

I don't mind if we have to copy/paste the URL manually.

Anyway thanks a lot for this great and already very useful addon! :)

**Comment by davidparsson** [comment]
Fixed in d56cf3f4, released in 2.11.

**Comment by davidparsson** [comment]
Remember that holding down one of the non-configured hotkeys will disable scrolling as well.

**Comment by Droyk** [comment]
Thanx wasn't expecting it.
