### ISSUE TITLE
Feature Request: Add more buttons to hold down to drag

### ISSUE THREAD

**Issue by Droyk** [davidparsson/scrollbar-anywhere#54]
Another feature request **Add more buttons to hold down to drag** means rightnow scrollbar only supports 3 mouse buttons right, middle & left I want you to give us more mouse buttons so I can drag whenever I want to without being afraid of site compatibility I have 6 mouse buttons which means 3 are the main middle, left & right and other 3 are not that main so in short if you implement this feature I will leave my 3 main buttons and drag with 3 buttons that are not my main buttons so this means there is no worry of site compatibility.   

**But remember this solution only works if the user have multiple mouse buttons like myself it doesn't work on those who only have 3 or 2 mouse buttons.**

**Comment by davidparsson** [comment]
This is a good idea, but according to my investigations it does not seem to be supported by JavaScript in Chrome. Should anyone discover anything else, please let me know.

**Comment by Droyk** [comment]
what do you mean it doesn't supported by javascript I have seen many extensions that have multiple buttons support!!

**Comment by davidparsson** [comment]
Care to give an example?

**Comment by Droyk** [comment]
Streamkeys

**Comment by davidparsson** [comment]
I still can't seem to find how it's done.

**Comment by Droyk** [comment]
I have 4 links for you plz see these and think something 
https://stackoverflow.com/search?q=detect+mouse+buttons
https://stackoverflow.com/questions/7906619/js-special-mouse-buttons
https://stackoverflow.com/questions/17526847/how-to-intercept-the-various-button-press-of-a-mouse-using-javascript?rq=1
https://stackoverflow.com/questions/2458730/how-to-detect-forward-and-back-mouse-button-events-in-delphi?rq=1

and it seems like my 2 additional mouse buttons can go backward and forward in any browser or any window explorer see the below thread 
https://stackoverflow.com/questions/2458730/how-to-detect-forward-and-back-mouse-button-events-in-delphi?rq=1 
so what do you think can you implement it

**Comment by davidparsson** [comment]
Thanks for your efforts, but those methods were the ones I've already tried, and they only seem to support the standard three mouse buttons (as comments in both answers suggest).

**Comment by Droyk** [comment]
Okay I made a script that lets me reconfigure my both 3 unused mouse buttons to a keyboard button 
for example my script can let me change my single mouse button to a 3 or 1 keyboard buttons. 

ctrl+alt+shift+win key+m = 4th mouse button
k = 5th mouse button
ctrl+q = 6th mouse button

if you add a keyboard support on your extension maybe this way I can use my additional mouse buttons.

**Comment by davidparsson** [comment]
That might be possible. I'm closing this since that feature is already requested in #43.
