### ISSUE TITLE
Feature Request: Work in Builtin PDF Viewer

### ISSUE THREAD

**Issue by duarteframos** [davidparsson/scrollbar-anywhere#55]
If possible make scrolling with this extension work in Builtin PDF Viewer

**Comment by Droyk** [comment]
Chrome doesn't give permission to let the extension run on chrome pages so for now developer can't do anything to make this extension work with Builtin PDF Viewer,

but this will be change in coming chrome builds soon chrome will give permission to let the extensions run on chrome pages so if the developer of this extension wants then this extension will work on Builtin PDF Viewer.

**Comment by duarteframos** [comment]
Ah what a shame, but I feared as much. Lets hope the developer does want it to run on PDF, would be a great addition.

Anyway, thanks for the answer, looking forward to future chrome builds :) Feel free to close this issue to keep tracker clean.

**Comment by Droyk** [comment]
>Feel free to close this issue to keep tracker clean.

Doesn't matter you close it or not developer won't give a damn he still not going to add it I think he abandoned this extension.

**Comment by davidparsson** [comment]
Closing, since this does not currently seem to be possible.
