### ISSUE TITLE
Some sites show strange behaviour

### ISSUE THREAD

**Issue by om22** [davidparsson/scrollbar-anywhere#60]
For example on mydealz.de scrolling doesn't work

**Comment by deathtrip** [comment]
i also have some sites not working since chromium 61 came out (like xvideos.com for example)

**Comment by davidparsson** [comment]
@om22, which version of Chrome are you using? On what OS? Which button do you use to scroll?

**Comment by om22** [comment]
Currently on Debian 9.1.0 with Chrome 61.0.3163.100. But under Windows 10 build 1703 (don't know my  Windows Chrome version at the moment) it doesn't work either

**Comment by deathtrip** [comment]
i use arch linux, with left button used for scrolling

**Comment by davidparsson** [comment]
Right. I can reproduce this with Chrome 61, but with Chrome 60 it worked
just fine. I'll try to find some time to fix this soon.

lör 23 sep. 2017 kl 10:55 skrev deathtrip <notifications@github.com>:

**Comment by davidparsson** [comment]
Just to clarify, I could reproduce this on mydealz.de, but not on the other site. Are there any other examples of sites where this extension does not work? mydealz.de seem to do other things that interfere with this extension as well, and I'm unsure if those can be handled in a general way.

**Comment by deathtrip** [comment]
https://www.phoronix.com/forums/ is another one i found

**Comment by vsemozhetbyt** [comment]
This FB note does not work for me in Chrome Canary: https://www.facebook.com/notes/conflict-intelligence-team/861712233981755/

**Comment by vsemozhetbyt** [comment]
Also, any twitter page seems to not work in Chrome Canary, e.g. https://twitter.com/v8js.

**Comment by deathtrip** [comment]
yeah, twitter also not working for me in chromium 61 on linux

**Comment by davidparsson** [comment]
Thanks, I'll investigate.

**Comment by davidparsson** [comment]
I've published `2.14` that should fix this. It should be available within an hour. Please let me know if you see any other issues with that version.

**Comment by vsemozhetbyt** [comment]
2.14 seems fixed in Chrome Canary 63. Thank you!
