### ISSUE TITLE
Any chance of Firefox port?

### ISSUE THREAD

**Issue by the-trooper0000** [davidparsson/scrollbar-anywhere#61]
Now that Firefox is very soon switching to WebExtension (nightly is already there), any chance you'll port this extensions?

Thanks in advance!
(Thanks on answering, I'm not presuming you'll do it just because I asked :D )

**Comment by davidparsson** [comment]
Nope, sorry, but I don't even have enough time to give this extension the attention it deserves. But you're welcome to take a look at the source code and give it a try yourself. 😁
