### ISSUE TITLE
Grab-and-drag style scrolling jumps to the top of the page

### ISSUE THREAD

**Issue by paraschas** [davidparsson/scrollbar-anywhere#63]
Hello, I use the Grab-and-drag style scrolling but frequently the page jumps to the top while holding the (middle) mouse button I use for scrolling. I feel that this happens more frequently when I make short movements of the page and maybe when I'm holding the button for multiple seconds, but I'm not really sure how to reproduce this bug. Any ideas of how to fix this?

My setup:
- Mouse button used when scrolling: middle mouse button
- Chrome version: 63.0.3239.108 (Official Build) (64-bit) (but this is a problem I have for more than a year)
- Operating system: Kubuntu 16.04.3 LTS

**Comment by davidparsson** [comment]
Thanks for reporting! How frequent is this occurring for you? Is it easily reproducible if browsing for a little while?

**Comment by paraschas** [comment]
It can happen from a couple of times each day up to several. As for the second question, your intuition might be right, as without being certain I think that the session length could be correlated with the occurrence of the bug.

**Comment by paraschas** [comment]
Hello, I don't think that the browsing session's length has anything to do with this bug, after all. There were multiple times that this behavior occurred in the past few days in pages opened only minutes ago. What could possibly be the issue?

**Comment by davidparsson** [comment]
How often is this occurring? I've tried reproducing this for a little while without any luck. Do you have any other extensions or other software that is activated when pressing the middle mouse button? If so, can you reproduce this with those disabled?

**Comment by paraschas** [comment]
Some days it happens dozens of times, and other days just once or maybe a couple. Unfortunately this isn't consistent.

As for the other installed extensions, I can't think of any that could interfere with Scrollbar Anywhere. Here they are in case you think of something: cVim, Google Docs Offline, Search in background tab, Secure Shell, Stylish - Custom themes for any website, Tampermonkey, uBlock Origin. I'll try to test browsing with all but uBlock Origin disabled, to confirm that this doesn't happen due to any of them.

A hint could be that it usually happens when I'm trying to fine-tune the position of the page on screen, for example when I want to move to the start of a section of a page, or center an image. This pixel-accurate movement seems to often trigger the bug, could it be that a variable gets assigned to zero due to rounding or a similar calculation?

**Comment by tenerhades** [comment]
@paraschas, are you using KDE in Kubuntu? I've had something like this happen in games when using GNOME 3, but not in the same games in i3.

In my case, the cursor was snapping because GNOME was resetting the xinput "Coordinate Transformation Matrix" property on my mouse. i3 doesn't handle any of that extra stuff, so using that (instead of gnome3) made the problem go away.

Are you able to test in a different desktop environment?

**Comment by paraschas** [comment]
Yes, I'm using KDE currently. So what you say is that the bug is independent of the extension and the browser itself? Is there a way to keep track of the specified xinput property? If it's exposed in some manner then its changes can be logged, and it would be easy to check for a reset of its value right after the bug occurs. (I might be able to test i3 or another desktop environment but only later in February.)

**Comment by tenerhades** [comment]
It might be independent of the extension and browser, yes. When I read your issue, I set my middle mouse to be the drag button and browsed around for a while and couldn't reproduce it. It sounds like @davidparsson wasn't able to reproduce it either. So it's possible some other factor is in play in your environment.

If you're using Grab-and-drag style scrolling and the page is snapping to the top, then the mouse may be snapping to the bottom of the screen. [Here](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1574667) is a similar bug from multiple users of Ubuntu 16.04 LTS. If that seems to match your issue, then many of those users are saying that [comment 32](https://bugs.launchpad.net/ubuntu/+source/xorg/+bug/1574667/comments/32) is a workable solution.

**Comment by paraschas** [comment]
I just got time to check the Ubuntu bug, thanks for researching it and looking for a solution! I think though that my issue is something different, as the pointer in my case doesn't move erratically, and also the problem never occurs to any other program that has a scrolling page, for example the pdf reader.

This is a difficult issue to debug, because it happens only very occasionally, a couple of times each day. I'll keep trying to find a way to reproduce it and I'll report here when I have something to help you make a fix. Apart from this, is there a way to provide you with debug or logging information on the extension? Could running it in Developer mode help somehow?

**Comment by tenerhades** [comment]
Yes, I've got some ideas for developer mode, but you'll need to find a way to predictably expose the behavior for it to be useful. I think if you enable "show debug noise in console", then all you'll see is a "drag update" when the problem occurs.

Is it a memory issue? Computers behave in "undefined" fashions when they're low on RAM. If you're running Chrome with only one tab after fresh reboot, does the problem ever occur?

**Comment by paraschas** [comment]
Thanks, I'll keep running the console for the extension and lookout for the debug output when the bug occurs.

As for the memory, I don't believe it's an issue, as I have 12GiB of RAM and very rarely does it get filled in day to day usage.

**Comment by davidparsson** [comment]
I'm closing this. Feel free to reopen or let me know if anybody finds out more details.

**Comment by paraschas** [comment]
The problem never went away. Actually in some Chrome update it became so bad that I've stopped using the extension altogether, which is a shame, because I really liked that way of scrolling.

I didn't manage to get any useful information on the issue, but please let me know if I could try something to get it resolved.

**Comment by davidparsson** [comment]
The only thing I can think of is to enable debug logging and try to see what that says when the problem occurs. But my guess is that it's platform specific in some way, since nobody else has reported this.

**Comment by paraschas** [comment]
That seems logical, so after I upgrade my Kubuntu installation during the next couple of weeks I'll check the functionality again and report back. Hopefully it will get resolved just by that.

**Comment by paraschas** [comment]
Happy New Year and thanks for the help with this issue. I haven't observed this faulty behavior in a couple of systems I'm using for quite some time now, so I believe this issue can be closed.

**Comment by davidparsson** [comment]
🎇🎆
