### ISSUE TITLE
doesn't work in default mode. same as 'grab and drag' now

### ISSUE THREAD

**Issue by hannesgrebin** [davidparsson/scrollbar-anywhere#72]
My setup:
- Mouse button used when scrolling: 
- Chrome version: 
- Operating system:

**Comment by davidparsson** [comment]
I think I need more details. What is it that does not work?

**Comment by davidparsson** [comment]
I believe that removing and installing the extension should reset all settings. Please let me know if that works for you.

That being said, I've never heard of this issue occurring before, so I don't really know what's going on.

**Comment by davidparsson** [comment]
I'm closing this, but please let me know if your still having problems.

**Comment by hannesgrebin** [comment]
Reinstalling would fix everything.
