### ISSUE TITLE
Unable to open menu on Right-click after update.

### ISSUE THREAD

**Issue by XCanG** [davidparsson/scrollbar-anywhere#74]
Previously I can **tap in place** and right click menu will show up, now even if I click and release **without scrolling** menu can't appear and blocked by addon. It only work on bugged `<a>` elements, where addon not work, or I can click keyboard `Menu` button, but this menu work only on selected elements, and if none is selected it always open in top-left, but anyway that's inconvenient.

My setup:
- Mouse button used when scrolling: RMB
- Chrome version: 74.0.3729.131 x64
- Operating system: Windows 10.0.17134 x64

**Comment by davidparsson** [comment]
Hi! Thanks for your report, and sorry for a terribly late response. I've been able to reproduce the issue and I'm working on a fix.
