### ISSUE TITLE
Enhancement Request:  Keep Cursor Stationary

### ISSUE THREAD

**Issue by nkormanik** [davidparsson/scrollbar-anywhere#75]
A paid alternative, ScrollNavigator, allows for stationary cursor -- cursor does not move up or down as one scrolls.  Is that at all possible in your case with ScrollbarAnywhere?  I'd love to see it.

My setup:
- Mouse button used when scrolling: 
- Chrome version: 
- Operating system:

**Comment by davidparsson** [comment]
Are you referring to another chrome application or a standalone software? It seems to be possible to do in a chrome extension, although it might show a chrome notification every time it's active so I'm not sure it would be smooth to use.

That said, I don't have the time needed to develop new features in this extension. Pull requests are accepted, if you're up for it yourself.

**Comment by nkormanik** [comment]
Thanks for getting back, David.

 

Scroll Navigator is a stand-alone Windows software:

DeskSoft - ScrollNavigator - Window scrolling helper <https://www.desksoft.com/ScrollNavigator.htm> 

 

It has the wonderful ability to keep the cursor stationary in one place, wherever you initially press the button.  So you can scroll up or down forever.  No need to keep repositioning your cursor when it gets to the top/bottom of the screen.

 

Unfortunately, Scroll Navigator only works with the right mouse button.  Not the left mouse button.

 

Your extension, Srollbar-anywhere, can be applied to the left mouse button, which is my preference.

 

Really, the only issue I have with Scrollbar-anywhere is I wish it would allow for keeping the mouse cursor in the same spot as where you initially press the button, so user doesn’t have to eventually reposition.  When button is pressed, just scroll, don’t allow the cursor to move.

 

Thanks!!

**Comment by davidparsson** [comment]
Ok. Getting completely identical functionality is simply not possible in a chrome extension due to limitations applied by Chrome.

I think I'll close this since I don't see a possibility to create a satisfying solution for this, but thanks for your suggestion anyway.
